### ISSUE TITLE
A file request of "home/jianhuiwei/rsch/jianhui/dataset/20news/train.json"

### ISSUE THREAD

**Issue by LieLieLieLieLie** [JianhuiWei7/FedLLM#1]
FileNotFoundError: File /home/jianhuiwei/rsch/jianhui/dataset/20news/train.json does not exist

**Comment by JianhuiWei7** [comment]
[test.json](https://github.com/user-attachments/files/17610768/test.json)
[train.json](https://github.com/user-attachments/files/17610769/train.json)
Here you are.

**Comment by LieLieLieLieLie** [comment]
Thanks!
2506733964
***@***.***
---- Replied Message ----
***@***.***>Date11/3/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [JianhuiWei7/FedLLM] A file request of "home/jianhuiwei/rsch/jianhui/dataset/20news/train.json" (Issue #1)
test.json
train.json
Here you are.

**Comment by LieLieLieLieLie** [comment]
I would like to express my gratitude for your contributions to the field of federated large models through your open-source project. 
I would like to follow up on my previous inquiry regarding FedLLM. Could you please let me know if there are any corresponding papers or references related to FedLLM? I would greatly appreciate any literature you could share.
2506733964
***@***.***
---- Replied Message ----
***@***.***>Date11/3/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [JianhuiWei7/FedLLM] A file request of "home/jianhuiwei/rsch/jianhui/dataset/20news/train.json" (Issue #1)
Closed #1 as completed.

**Comment by JianhuiWei7** [comment]
Thanks a lot, I didn't expect that someone would look at my code even without a .md file.
Here are some related papers.  
Towards Building the Federated GPT: Federated Instruction Tuning
FedNLP: Benchmarking Federated Learning Methods for Natural Language Processing Tasks
SLoRA: Federated Parameter Efficient Fine-Tuning of Language Models
And,  you can find more papers by tracking down papers referencing these with Google scholar search engine.
Good Luck !

**Comment by JianhuiWei7** [comment]
By the way. This is my undergraduate project. I can not directly provide my academic dissertation to you. But, you can read the papers mentioned above to gain more insights. Good Luck!

**Comment by LieLieLieLieLie** [comment]
Thank you for your response and for clarifying the privacy aspects of your undergraduate project. I am currently starting my research in the field of federated large models, and I believe the papers you provide will be very helpful for my studies. Thanks again!
2506733964
***@***.***
---- Replied Message ----
***@***.***>Date11/3/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [JianhuiWei7/FedLLM] A file request of "home/jianhuiwei/rsch/jianhui/dataset/20news/train.json" (Issue #1)
By the way. This is my undergraduate project. I can not directly provide my academic dissertation to you. But, you can read the papers mentioned above to gain more insights. Good Luck!
